type SEOProps = {
	// TODO: Add SEO props
};

export function SEO(): JSX.Element {
	return (
		<>
			<title>UWU Games</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<meta
				name="description"
				content="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
			/>
			<meta name="keywords" content="UWU, UWU GAMES, Games, PC" />
			<meta name="robots" content="noindex, nofollow" />
			<meta property="og:title" content="UWU Games - Best UWU games" />
			<meta property="og:type" content="website" />
			<meta property="og:url" content="https://uwu.games" />
			<meta property="og:image" content="https://uwu.games/logo.png" />
			<meta
				property="og:description"
				content="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
			/>
			<meta property="og:site_name" content="UWU Games" />
			<meta property="og:image:type" content="image/png" />
			<meta property="og:image:width" content="1200" />
			<meta property="og:image:height" content="630" />
			<meta name="twitter:card" content="summary" />
			<meta name="twitter:title" content="UWU Games - Best UWU games" />
			<meta
				name="twitter:description"
				content="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
			/>
			<meta name="twitter:image" content="https://uwu.games/logo.png" />
		</>
	);
}
