import { FloatingPanel } from "@/atoms/floatingPanel";
import { Watermark } from "@/atoms/watermark";
import { Nav } from "@/molecules/nav";
import { Soon } from "@/molecules/soon";
import { Colors } from "@/utils/theme";
import Head from "next/head";

export default function Home() {
	const openDiscord = () => {
		window.open("https://discord.gg/tddUyP9R", "_blank");
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Nav />

			<main className='flex mt:10% flex:col'>
				<Soon />
				<p
					className={`f:32 f:${Colors.Pink} f:bold cursor:pointer`}
					onClick={openDiscord}
				>
					Join Us
				</p>
			</main>

			<Watermark />
			<FloatingPanel />
		</>
	);
}
